project_name: wrangell
dist: bin/
release:
  skip_upload: true
builds:
  - id: wrangell
    env:
      - CGO_ENABLED=0
    main: ./cmd
    binary: wrangell
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/1outres/wrangell.Version={{.Version}}
dockers:
  - image_templates:
      - "ghcr.io/1outres/wrangell:{{ .Version }}-amd64"
    use: buildx
    dockerfile: ./Dockerfile
    ids:
      - wrangell
    extra_files:
      - LICENSE
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "ghcr.io/1outres/wrangell:{{ .Version }}-arm64"
    use: buildx
    dockerfile: ./Dockerfile
    ids:
      - wrangell
    extra_files:
      - LICENSE
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: "ghcr.io/1outres/wrangell:{{ .Version }}"
    image_templates:
      - "ghcr.io/1outres/wrangell:{{ .Version }}-amd64"
      - "ghcr.io/1outres/wrangell:{{ .Version }}-arm64"
  - name_template: "ghcr.io/1outres/wrangell:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/1outres/wrangell:{{ .Version }}-amd64"
      - "ghcr.io/1outres/wrangell:{{ .Version }}-arm64"
changelog:
  use: github-native