apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rabbitmq
  template:
    metadata:
      labels:
        run: rabbitmq
    spec:
      hostname: rabbitmq
      containers:
        - name: rabbitmq
          command:
            - rabbitmq-server
          args: []
          image: rabbitmq:4
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: wrangell
            - name: RABBITMQ_DEFAULT_PASS
              value: wrangell
          ports:
            - containerPort: 5672