---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - wrangell.loutres.me
  resources:
  - actions
  - events
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wrangell.loutres.me
  resources:
  - triggers/status
  verbs:
  - get
  - patch
  - update
