# permissions for end users to edit triggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wrangell
    app.kubernetes.io/managed-by: kustomize
  name: trigger-editor-role
rules:
- apiGroups:
  - wrangell.loutres.me
  resources:
  - triggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wrangell.loutres.me
  resources:
  - triggers/status
  verbs:
  - get
