apiVersion: wrangell.loutres.me/v1alpha1
kind: Trigger
metadata:
  labels:
    app.kubernetes.io/name: wrangell
    app.kubernetes.io/managed-by: kustomize
  name: trigger-sample
spec:
  event: me.loutres.wrangell.sample
  conditions:
    - "user.age > 18 && user.age < 30"
    - "user.name != 'root'"
    - "!(message contains 'Fuck')"
  actions:
    - action: me.loutres.wrangell.sample
      params:
        - name: source
          fromYaml: "Kubernetes"
        - name: message
          fromData:
            name: message
        - name: username
          fromData:
            name: user.name